### ISSUE TITLE
Project description link goes to a 404 page

### ISSUE THREAD

**Issue by tealamore** [passmarked/spellcheck#1]
If you click the link under the project description, it goes to a 404 page on passmarked.

**Comment by Johanndutoit** [comment]
Thanks for reporting, we are currently finishing the website so not all the pages are live. The rule code was just ready so we opted to get it all live and ready for use. Will close the issue once our new website is online.

If you anything anything else please do share.

**Comment by Johanndutoit** [comment]
Initial version is live, closing :)
