### ISSUE TITLE
Should not check within <script/> tags

### ISSUE THREAD

**Issue by BarryBotha** [passmarked/spellcheck#8]
In:
```
<script>
function closePopupLitebox() {window.parent.postMessage('closePopupLitebox', '*');}
</script>
```
It picks up `Popup` as a spelling mistake.
We should not be checking JS code for spelling mistakes.

**Comment by Johanndutoit** [comment]
MMM this might a coincidence as we only check:

```
var elementTags = [

  'body h1',
  'body h2',
  'body h3',
  'body h4',
  'body h5',
  'body h6',
  'body p',
  'body li',
  'body a'

];
```

Updated to check for both the tag and spelling mistake when looking for the line in the source code, see https://github.com/passmarked/spellcheck/pull/11 for release coming down in a few minutes

**Comment by Johanndutoit** [comment]
Fix is on it's way out, see https://github.com/passmarked/spellcheck/pull/11
